### ISSUE TITLE
package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by Dereck0602** [zhouj8553/FlipDA#1]
Hi, when I install the environment with requirements.txt, the version of torch, transformers and sentence-transformers have conflicting dependencies
![1](https://user-images.githubusercontent.com/52696292/129894265-3ba0ee75-20fe-4d0c-bd0e-01e69f9d5f75.jpg)
![2](https://user-images.githubusercontent.com/52696292/129894309-7da8df33-040d-4fbb-90db-db7cbe8f8a0a.jpg)

**Comment by zhouj8553** [comment]
Thanks for your attention. Sorry that I forget to recheck it after I put it on GitHub. Sentence-transformers is not used in this project in the final version, you can just remove it and I have also removed the unused class with regard to it in my project. Also, I have reuploaded some of the files, you can redownload them.

**Comment by Dereck0602** [comment]
Thank you for the reply.
