### ISSUE TITLE
Suitable for Chinese language?

### ISSUE THREAD

**Issue by LangDaoAI** [zhouj8553/FlipDA#3]
Hi,

Is the model suitable for Chinese language?

Thanks!

**Comment by zhouj8553** [comment]
Thanks for your attention.
Sorry that we do not provide a Chinese version (We only experiment on SuperGLUE). You can adapt it yourself. For example, change to a base model that is pre-trained on Chinese, and augment data that are suitable for your task (change the file 'genaug/total_gen_aug.py'). We think the pipline is the same, and most of the codes could be reused.

**Comment by LangDaoAI** [comment]
Thanks detailed reply very much !

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
